# Generated by Django 3.2.4 on 2022-03-24 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='customer_birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
