# Generated by Django 3.2.4 on 2022-03-28 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(default=None)),
                ('image_url', models.URLField(default=None)),
                ('page_url', models.URLField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
